model_name_or_path: Qwen3-8B
trust_remote_code: true
flash_attn: fa2

stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_target: all

dataset: wo_MDA_train
template: qwen
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8
val_size: 0.01

output_dir: checkpoints/wo_MDA
logging_steps: 5
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_total_limit: 3

per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 200

enable_thinking: false